# Generated by Django 5.1.4 on 2025-09-30 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price_without_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price_with_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='price', to='products.product')),
            ],
        ),
    ]
