# Generated by Django 5.1.4 on 2025-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status_cart',
            field=models.CharField(choices=[('open', 'Aberto'), ('pendent', 'Pendente'), ('finalized', 'Finalizado'), ('canceled', 'Cancelado')], default='open', max_length=9),
        ),
    ]
