# Generated by Django 5.1.4 on 2025-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
