# Generated by Django 5.1.4 on 2025-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('paid', 'Finalizado com Sucesso'), ('canceled', 'Cancelado'), ('error', 'Erro')], default='pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('system', 'Sistema'), ('web', 'Internet')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Cartão de Credito'), ('debit_card', 'Cartão de Debito'), ('pix', 'Pix'), ('cash', 'Dinheiro')], max_length=12, null=True),
        ),
    ]
